var Login = require("./User/Login");
var Upload = require("./Documents/Upload");
var Download = require("./Documents/Download");
var Register = require("./User/Register");
var Folder = require("./Folder/Folder");
var Delete = require("./Folder/DeleteFolder");
var ChangInfor = require("./User/ChangInfor");
var ChangNames = require("./Folder/ChangeName");
var ChangePassWord = require("./Folder/ChangePassWord");
var GetFolder = require("./Folder/GetFolder");
var Getdocumments = require("./Documents/GetDocument");
var DeleteDocument = require("./Documents/DeleteDocument");
var GetFileFolder = require("./Folder/GetFileFolder");
var CheckPass = require("./Folder/CheckPass");
var Search = require("./Documents/Search");
module.exports = function (app) {
  console.log("this is to to Controllers");
  Login(app);
  Upload(app);
  Download(app);
  Register(app);
  Folder(app);
  Delete(app);
  ChangInfor(app);
  ChangNames(app);
  ChangePassWord(app);
  GetFolder(app);
  Getdocumments(app);
  DeleteDocument(app);
  GetFileFolder(app);
  CheckPass(app);
  Search(app);
};
